### ISSUE TITLE
How to cache the basemap?

### ISSUE THREAD

**Issue by parcool** [Esri/arcgis-runtime-demos-android#46]
When i load my basemap by internet first,if i re-open my app,it needs download the data from server agian.how to cache the loaded data of basemap????
I do not found the api about this! so is a question or issue?

**Comment by parcool** [comment]
another question is my app has more than one activity with the map,so each activity needs load the basemap agian?

**Comment by doneill** [comment]
@parcool This is best asked on the [geonet forum](https://geonet.esri.com/community/developers/native-app-developers/arcgis-runtime-sdk-for-android), but since you are here I will offer comments.  There is no API for caching data in the ArcGIS Android SDK so you as a developer have to manage cache of objects yourself.  We do have an example of caching retrieved Basemaps in the MaterialBasemaps [MainActivity](https://github.com/Esri/arcgis-runtime-demos-android/blob/master/2015-DS/MaterialBaseMaps/app/src/main/java/com/esri/runtime/android/materialbasemaps/ui/MainActivity.java) which shows one way to accomplish this using the [PersistBasemapItem](https://github.com/Esri/arcgis-runtime-demos-android/blob/master/2015-DS/MaterialBaseMaps/app/src/main/java/com/esri/runtime/android/materialbasemaps/model/PersistBasemapItem.java) class.

**Comment by parcool** [comment]
@doneill thanks a lot!!!
